Back End/project-grails-main/grails-app/domain/fr/itu/mbds/grails/Annonce.groovy
package fr.itu.mbds.grails

class Annonce {

    String      title
    String      description
    Float       price
    Boolean     status = Boolean.FALSE
    Date        dateCreated
    Date        lastUpdated
    List        illustrations

    static hasMany = [illustrations: Illustration]

    static belongsTo = [author: User]

    static constraints = {
        title nullable: false, blank: false
        description nullable: false, blank: false
        price min: 0F, nullable: false
        status nullable: false
    }

    static mapping = {
        description type: 'text'
    }
}

Back End/project-grails-main/grails-app/controllers/fr/itu/mbds/grails/AnnonceController.groovy
package fr.itu.mbds.grails

import grails.plugin.springsecurity.annotation.Secured
import grails.validation.ValidationException

import java.time.LocalDateTime
import java.time.format.DateTimeFormatter

import static org.springframework.http.HttpStatus.*

@Secured(['ROLE_ADMIN','ROLE_MODO'])
class AnnonceController {

    AnnonceService annonceService
    IllustrationService illustrationService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond annonceService.list(params), model:[annonceCount: annonceService.count()]
    }

    def show(Long id) {
        def annonceDet = annonceService.get(id)
        render (view: 'show', model:[annonceDet:annonceDet]);
        def illustration = annonceDet.getIllustrations()
        respond annonceService.get(id)
    }

    def create() {
        def usersAuthors = User.all
        render (view: 'create', model:[userList:usersAuthors]);
        respond new Annonce(params)
    }

    def save(Annonce annonce) {
        if (annonce == null) {
            notFound()
            return
        }
        String imageUploadPath= grailsApplication.config.getProperty('illustrations.path')
        request.getMultiFileMap().illustration.each {

            if(it && !it.empty){
                it.transferTo(new File("${imageUploadPath}${it.originalFilename}"))
                flash.message="your.sucessful.file.upload.message"
            }
            else{
                flash.message="your.unsucessful.file.upload.message"
            }
            annonce.addToIllustrations(new Illustration(filename: "${it.originalFilename}"))
        }

        try {
            annonceService.save(annonce)
        } catch (ValidationException e) {
            respond annonce.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'annonce.label', default: 'Annonce'), annonce.id])
                redirect annonce
            }
            '*' { respond annonce, [status: CREATED] }
        }
    }

    def edit(Long id) {
        respond annonceService.get(id)
    }

    def update(Annonce annonce) {
        if (annonce == null) {
            notFound()
            return
        }

        try {
            annonceService.save(annonce)
        } catch (ValidationException e) {
            respond annonce.errors, view:'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'annonce.label', default: 'Annonce'), annonce.id])
                redirect annonce
            }
            '*'{ respond annonce, [status: OK] }
        }
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        annonceService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'annonce.label', default: 'Annonce'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    def saveImage(){
        def annonce = annonceService.get(params.idA)
        String imageUploadPath= grailsApplication.config.getProperty('illustrations.path')
        request.getMultiFileMap().illustration.each {

            if(it && !it.empty){
                it.transferTo(new File("${imageUploadPath}${it.originalFilename}"))
                flash.message="your.sucessful.file.upload.message"
            }
            else{
                flash.message="your.unsucessful.file.upload.message"
            }
            annonce.addToIllustrations(new Illustration(filename: "${it.originalFilename}"))
        }
        this.update(annonce)
    }
    def uploadImage(){
        def file=request.getFile('image')
        String imageUploadPath=grailsApplication.config.imageUpload.path
        try{
            if(file && !file.empty){
                file.transferTo(new File("${imageUploadPath}/${file.name}"))
                flash.message="your.sucessful.file.upload.message"
            }
            else{
                flash.message="your.unsucessful.file.upload.message"
            }
        }
        catch(Exception e){
            log.error("Your exception message goes here",e)
        }

    }


    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'annonce.label', default: 'Annonce'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

Back End/project-grails-main/grails-app/controllers/fr/itu/mbds/grails/UserController.groovy
package fr.itu.mbds.grails

import grails.plugin.springsecurity.annotation.Secured
import grails.validation.ValidationException
import static org.springframework.http.HttpStatus.*

@Secured(['ROLE_ADMIN','ROLE_MODO'])
class UserController {

    UserService userService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond userService.list(params), model:[userCount: userService.count()]
    }

    def show(Long id) {
        respond userService.get(id)
    }

    def create() {
        def role = Role.findByAuthority(params.role)
        def user = new User(params).save()
        UserRole.create(user, role , true)
        respond new User(params)
    }

    def save(User user) {
        if (user == null) {
            notFound()
            return
        }

        try {
            userService.save(user)
        } catch (ValidationException e) {
            respond user.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'user.label', default: 'User'), user.id])
                redirect user
            }
            '*' { respond user, [status: CREATED] }
        }
    }

    def edit(Long id) {
        respond userService.get(id)
    }

    def update(User user) {
        if (user == null) {
            notFound()
            return
        }

        try {
            println params.role
            def role = Role.findByAuthority(params.role)
            def ancienUser = userService.get(user.id)
            def ancienRole = Role.findByAuthority(ancienUser.getAuthorities().authority[0])
            UserRole.remove(user, ancienRole)
            UserRole.create(user, role , true)
            userService.save(user)
        } catch (ValidationException e) {
            respond user.errors, view:'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'user.label', default: 'User'), user.id])
                redirect user
            }
            '*'{ respond user, [status: OK] }
        }
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        userService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'user.label', default: 'User'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'user.label', default: 'User'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

Back End/project-grails-main/grails-app/views/annonce/create.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main"/>
    <asset:stylesheet src="create.css"/>
    <g:set var="entityName" value="${message(code: 'annonce.label', default: 'Annonce')}"/>
    <title><g:message code="default.create.label" args="[entityName]"/></title>
</head>

<body>
<a href="#create-annonce" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                                default="Skip to content&hellip;"/></a>

<content tag="nav">
    <ul>
        <li>
            <g:link class="list navigation-link" action="index"><i class='bx bx-detail' ></i><g:message code="default.list.label" args="[entityName]" /></g:link>
        </li>

    </ul>
</content>
<div id="create-annonce" class="content scaffold-create" role="main">
    <h2 class="titre mb-5">Création Annonce</h2>
    <g:if test="${flash.message}">
        <div class="position-fixed bottom-0 end-0 p-3 " style="z-index: 11">
            <div id="liveToast" class="toast show" role="alert" aria-live="assertive" aria-atomic="true">
                <div class="toast-header">
                    <span  class="rounded me-2" style="padding: 1em;background: #0a53be"> </span>
                    <strong class="me-auto">LeCoinCoin</strong>
                    <small>Maintenanto</small>
                    <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
                </div>
                <div class="toast-body">
                    ${flash.message}
                </div>
            </div>
        </div>
    </g:if>
    <g:hasErrors bean="${this.annonce}">
        <ul class="errors" role="alert">
            <g:eachError bean="${this.annonce}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                        error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
    <g:form class="container" controller="annonce" action="save" method="POST" enctype="multipart/form-data">
        <div class="row">
            <div class="col-8 offset-2">

                 <div class="row">
                    <div class=" col mb-3">
                        <label for="title" class="form-label">Titre <span class="required-indicator">*</span></label>
                        <input type="text" name="title" class="form-control" value="" required="" id="title">
                    </div>
                 </div>
                <div class="row">
                    <div class=" col mb-3">
                        <label for="price" class="form-label">Prix <span class="required-indicator">*</span></label>
                        <input type="number decimal" name="price" class="form-control" alue="" required="" min="0.0" id="price">
                    </div>
                    <div class=" col mb-3">
                        <label for="author" class="form-label">Auteur <span class="required-indicator">*</span></label>
                        <select class="form-select" name="author.id" required="" id="author">
                            <g:each var="child" in="${userList}">
                                <option value="${child.id}">${child.username}</option>
                            </g:each>

                        </select>
                    </div>

                </div>
                <div class="row">
                    <div class=" col mb-3">
                        <label for="description" class="form-label">Description <span class="required-indicator">*</span></label>
                        <textarea class="form-control" name="description"  value="" required="" id="description" rows="3"></textarea>
                    </div>
                </div>
                <div class="row">
                    <div class=" col mb-3">
                        <label for="illustration" class="form-label">Illustrations <span class="required-indicator">*</span></label>
                        <input class="form-control" type="file"
                               id="illustration" name="illustration"
                               accept="image/png, image/jpeg" multiple/>
                    </div>
                </div>
                <div class="row">
                    <div class=" col mb-3">
                        <label for="status">Status</label>
                        <input type="hidden" name="_status"><input type="checkbox" name="status" id="status">
                    </div>
                </div>

%{--                <label for="illustration">Illustrations</label>--}%
%{--                <input class="textfield" type="file"--}%
%{--                       id="illustration" name="illustration"--}%
%{--                       accept="image/png, image/jpeg" multiple/>--}%

%{--                <div class="checkboxContainer">--}%
%{--                <label for="status">Status</label>--}%
%{--                <input type="hidden" name="_status"><input type="checkbox" name="status" id="status">--}%
%{--                </div>--}%


                <div class="row">
                    <div class=" col text-center">
                        <g:submitButton name="create" class="save buttonSubmit btn-primary mt-5"
                                        value="Créer"/>
                    </div>
                </div>
            </div>
        </div>
    </g:form>

</div>
</body>
</html>

Back End/project-grails-main/grails-app/views/annonce/edit.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main" />
    <g:set var="entityName" value="${message(code: 'annonce.label', default: 'Annonce')}" />
    <title><g:message code="default.edit.label" args="[entityName]" /></title>
%{--    <asset:stylesheet src="annonce.css"/>--}%
</head>
<body>
<a href="#edit-annonce" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
<content tag="nav">
    <ul>
        <li>
            <g:link class="create navigation-link" action="create"><i class='bx bx-list-plus'></i><g:message code="default.new.label" args="[entityName]" /> </g:link>
        </li>
        <li>
            <g:link class="list navigation-link" action="index"><i class='bx bx-detail' ></i><g:message code="default.list.label" args="[entityName]" /></g:link>
        </li>

    </ul>
</content>
<div id="edit-annonce" class="content scaffold-edit" role="main">
    <h4 style="text-align: center; font-size: 2em" class="mt-3 mb-4"><g:message code="default.edit.labe" default="Mis à jour annonce" args="[entityName]" /></h4>
    <g:if test="${flash.message}">
        <div class="position-fixed bottom-0 end-0 p-3 " style="z-index: 11">
            <div id="liveToast" class="toast show" role="alert" aria-live="assertive" aria-atomic="true">
                <div class="toast-header">
                    <span  class="rounded me-2" style="padding: 1em;background: #0a53be"> </span>
                    <strong class="me-auto">LeCoinCoin</strong>
                    <small>Maintenanto</small>
                    <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
                </div>
                <div class="toast-body">
                    ${flash.message}
                </div>
            </div>
        </div>
    </g:if>
    <g:hasErrors bean="${this.annonce}">
        <ul class="errors" role="alert">
            <g:eachError bean="${this.annonce}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
    <g:form resource="${this.annonce}" method="PUT">
        <g:hiddenField name="version" value="${this.annonce?.version}" />
        <fieldset class="form">

%{--            <g:each in="annonce">${it.illustrations}</g:each>--}%
            <div class="row mb-3">
                <div class="col">
                    <label for="title" class="form-label">Title</label>
                    <g:textField class="form-control" name="title" value="${this.annonce.title}" id="title"/>
                </div>
                <div class="col">
                    <label for="price" class="form-label">Price</label>
                    <g:textField  type="number decimal" class="form-control" name="price" value="${this.annonce.price}" id="price"/>
                </div>
            <div class="col"> <f:field  bean="annonce" property="author"  /></div>
                <div class="col">
                    <label for="status">Status</label><input type="hidden" name="_status">
                    <input type="checkbox" name="status" checked="checked" id="status">
                </div>
            </div>
            <div class="row">
                <div class="mb-3">
                    <label for="description" class="form-label">Description</label>
                    <g:textArea name="description"  class="form-control"  id="description" value="${this.annonce.description}"/>
                </div>
            </div>

        </fieldset>
        <fieldset class="text-center">
            <input class="save btn btn-warning " type="submit" value="${message(code: 'default.button.update.label', default: 'Mettre à jour')}" />
        </fieldset>
    </g:form>
%{--    <div class="row">--}%
%{--        <span id="illustrations-label" class="property-label">Illustrations</span>--}%
%{--        <div class="property-value" aria-labelledby="illustrations-label">--}%
%{--            <div style="list-style: none;display: flex;--}%
%{--            justify-content: space-between;--}%
%{--            align-items: center;">--}%
%{--                <g:each var="child" in="${this.annonce.illustrations}">--}%
%{--                    <g:if test="${child != null}">--}%
%{--                        <div style="position: relative" class="mt-3">--}%
%{--                            <asset:image src="${child.filename}" class="shadow-sm imageAsinaHover" style="width: 10em;height: 15em;object-fit: cover;border-radius: 15px"/>--}%
%{--                        </div>--}%
%{--                    </g:if>--}%
%{--                </g:each>--}%
%{--            </div>--}%


%{--        </div>--}%
%{--    </div>--}%
</body>
</html>

Back End/project-grails-main/grails-app/views/annonce/index.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main" />
    <g:set var="entityName" value="${message(code: 'annonce.label', default: 'Annonce')}" />
    <title><g:message code="default.list.label" args="[entityName]" /></title>
    <asset:stylesheet src="backoffice.css"/>
</head>
<body>
<content tag="nav">
    <ul>
        <li>
            <g:link class="create navigation-link" action="create"><i class='bx bx-list-plus'></i><g:message code="default.new.label" args="[entityName]" /> </g:link>
        </li>
    </ul>
</content>
<g:if test="${flash.message}">
    <div class="position-fixed bottom-0 end-0 p-3 " style="z-index: 11">
        <div id="liveToast" class="toast show" role="alert" aria-live="assertive" aria-atomic="true">
            <div class="toast-header">
                <span  class="rounded me-2" style="padding: 1em;background: #0a53be"> </span>
                <strong class="me-auto">LeCoinCoin</strong>
                <small>Maintenanto</small>
                <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
            </div>
            <div class="toast-body">
                ${flash.message}
            </div>
        </div>
    </div>
</g:if>
%{--        <div class="row">--}%
%{--            <div class="col-md-3 " >--}%
%{--                <div class="card shadow rounded">--}%
%{--                    <asset:image src="undraw_Happy_announcement_re_tsm0.png" class="card-img-top"/>--}%
%{--                    <div class="card-body">--}%
%{--                        <h4 class="card-title">CRUD Annonce</h4>--}%
%{--                        <p class="card-text">This is some text within a card body.</p>--}%
%{--                    </div>--}%
%{--                </div>--}%
%{--            </div>--}%
%{--            <div class="col-md-9" >--}%
%{--                <div class="card">--}%
%{--                    <div class="card-body">--}%
%{--                        <h5 class="card-title">Liste des annonces présents dans la base</h5>--}%
%{--                        <div id="list-annonce" class="content scaffold-list mt-5" role="main">--}%
%{--                            <g:if test="${flash.message}">--}%
%{--                                <div class="message" role="status">${flash.message}</div>--}%
%{--                            </g:if>--}%
%{--                            <f:table class="table table-bordered" collection="${annonceList}"  />--}%

%{--                            <div class="pagination">--}%
%{--                                <g:paginate max='5' total="${annonceCount ?: 0}"  />--}%
%{--                            </div>--}%
%{--                        </div>--}%
%{--                    </div>--}%
%{--                </div>--}%
%{--            </div>--}%
%{--        </div>--}%

<div class="row mb-2">
    <div class=" entete">
        %{--            <asset:image src="undraw_Happy_announcement_re_tsm0.png" class="card-img-top"/>--}%
        <div class="card-body">
            <h4 class="card-title">Liste des annonces </h4>
            <p class="card-text">Le nombre total d'annonces actuel est ${annonceCount}</p>
        </div>
    </div>
</div>

<g:each var="a" in="${annonceList}">
    <div class="row mt-4 ">
        <div class="card cardAnnonce shadow">
            <div class="card-body">
                <div class="imageCardPart">
                    <div>
                        <g:each var="child" in="${a.getIllustrations()}">
                            <g:if test="${child != null}">
                                <li class="mb-1">
                                    <asset:image src="${child.filename}" class="img-thumbnail"/>
                                </li>
                            </g:if>
                        </g:each>
                    </div>
                    <g:if test="${a.getIllustrations()[0] != null}">
                        <div class="firstImage mx-2">
                            <asset:image src="${a.getIllustrations()[0].filename}" class="img-thumbnail"/>
                        </div>
                    </g:if>
                </div>
                <div class="titreCardPart">
                    <p class="card-title">${a.title} </p>
                    <div class="prixCardPart">
                        <g:formatNumber number="${a.price}" type="number" maxFractionDigits="0" /><span>,00€</span>
                    </div>
                    <p class="descCardPart"> ${a.description}</p>
                </div>


                <div class="actionCardPart">
                    <a href="show/${a.id}"><button type="button" class="btn btn-outline-secondary">Voir le produit</button></a>
                    <a href="edit/${a.id}"><button type="button" class="btn btn-outline-warning">Modifier le produit</button></a>
                    <g:form resource="${a}" method="DELETE">
                        <button class="delete btn btn-outline-danger" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Voulez-vous vraiment supprimer ce produit ?')}');" > Supprimer le produit</button>
                    </g:form>
                </div>

            </div>
        </div>
    </div>
</g:each>

</body>